using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace Poliomyelitis
{
    /// <summary>
    /// Логика взаимодействия для MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        public string[] Polio;

        static double compare2Polio(string first, string second)
        {
            double comp = 0;
            for (int i = 0; i < first.Length; i++)
            {
                if (first[i] == second[i])
                    comp++;
            }
            return Math.Round((comp / first.Length) * 100, 5); //В процентах
        }

        private void buttonStart_Click(object sender, RoutedEventArgs e)
        {
            listBoxComp.Items.Clear();
            Polio = new string[10];
            Polio[0] = "GGTTTGGGCCGGATGCTCGAGAGCATGATTGACAACACAGTCCGCGAAACAGTAGGGGCTTCAACCTCTCGGGACGCTCTCCCAAACACCGAGGCCAGCGGCCCAGCCCACTCCAAGGAAATTCCGGCGCTCACCGCAGTAGAGACGGGGGCCACAAACCCGTTGGTTCCCTCAGACACCGTACAAACTAGACATGTCATACAGCACAGATCGCGGTCAGAGTCCAGTGTTGAGTCCTTCTTCGCACGCGGTGCGTGTGTTACCATAATGACAGTGGACAATTCGGCCTCCACTACGTCAAAAGACAAGTTATTCTCTGTGTGGAAAATCACGTACAAGGACACTGTGCAGTTGAGGAGAAAATTAGAGTTTTTCACTTATTCCAGGTTTGACATGGAGTTCACTTTTGTAATCACAGCAAACTTTACAGAGACCAATAATGGACATGCTTTGAACCAGGTCTATCAAATCATGTATGTGCCACCAGGCGCACCAGTGCCAGAAAAGTGGGATGATTATACTTGGCAAACATCATCGAACCCATCAATTTTCTACACATACGGCACAGCACCGGCCCGCATCTCCGTACCGTACGTTGGTATATCAAATGCCTACTCACACTTTTATGACGGGTTTTCTAAAGTACCGTTGAAAGATCAATCAGCGGAGCTTGGTGACTCACTTTATGGTGCTGCTTCCCTGAATGACTTTGGCATTTTGGCTGTGAGGGTGGTTAACGACCATAATCCAACCAAGGTCACTTCCAAGATTAGGGTGTACTTAAAACCCAAACACATCAGAGTGTGGTGCCCCCGCCCACCGAGGGCAGTGGCGTATTACGGTCCGGGAGTGGACTACAAGGATGGGACGCTCGCTCCCCTTTCCACCAAAGACCTGACCACGTAT";
            Polio[1] = "GGTTTGGGCCAGATGCTCGAGAGCATGATTGACAACACAGTCCGCGAAACAGTAGGGGCTTCAACCTCTCGGGACGCTCTCCCAAACACCGAGTCCAGCGGCCCAGCCCACTCCAAGGAAATTCCGGCGCTCACCGCAGTAGAGACGGGAGCCACAAACCCGTTGGTTCCCTCAGACACCGTACAAACTAGACATGTCATACAGCACAGATCGCGGTCAGAGTCCAGTGTTGAGTCCTTCTTCGCACGCGGTGCGTGTGTTACCATAATGACAGTGGACAATTCGGCCTCCACTACGTCAAAAGACAAGTTATTCTCTGTGTGGAAAATCACGTACAAGGACACTGTGCAGTTGAGGAGAAAATTAGAGTTTTTCACTTATTCCAGGTTTGACATGGAGTTCACTTTTGTGATCACAGCAAACTTTACAGAGACCAATAATGGACATGCTTTGAACCAGGTCTATCAAATCATGTATGTGCCACCAGGCGCACCAGTGCCAGAAAAGTGGGATGATTATACTTGGCAAACATCATCGAACCCATCAATTTTCTACACATACGGCACAGCACCGGCCCGCATCTCCGTACCGTACGTTGGTATATCAAATGCCTACTCACACTTTTATGACGGGTTTTCTAAAGTACCGCTGAAAGATCAATCAGCGGAGCTTGGTGACTCACTTTACGGTGCTGCTTCCCTGAATGACTTTGGCATTTTGGCTGTGAGGGTGGTTAACGACCATAATCCAACCAAGGTCACCTCCAAGATTAGGGTGTACTTAAAACCCAAACACATCAGAGTGTGGTGCCCCCGCCCACCGAGGGCAGTGGCGTATTACGGCCCGGGAGTGGACTACAAGGATGGGACGCTCGCTCCCCTTTCCACCAAAGAACTGACCACGTAT";
            Polio[2] = "GGTTTGGGCCAGATGCTCGAGAACATGATTGACAACACAGTCCGCGAAACAGTAGGGGCTTCAACCTCTCGGGACGCTCTCCCAAACACCGAGTCCAGCGGCCCAGCCCACTCCAAGGAAATTCCGGCGCTCACCGCAGTAGAGACGGGAGCCACAAACCCGTTGGTTCCCTCAGACACCGTACAAACTAGACATGTTATACAGCACAGATCGCGGTCAGAGTCCAGTGTTGAGTCCTTCTTCGCACGCGGTGCGTGTGTTACCATAATGACAGTGGACAATTCGGCCTCTACTATGTCAAAAGACAAGTTATTCTCTGTGTGGAAAATCACGTACAAGGACACTGTGCAGTTGAGGAGAAAATTAGAGTTTTTCACTTATTCCAGGTTTGACATGGAGTTCACTTTTGTAATCACAGCAAACTTTACAGAGACCAATAATGGACATGCTTTGAACCAGGTCTATCAAATCATGTATGTGCCACCAGGCGCACCAGTGCCAGAAAAGTGGGATGATTATACTTGGCAAACATCATCGAACCCATCAATTTTCTACACATACGGCACAGCACCGGCCCGCATCTCCGTACCGTACGTTGGTATATCAAATGCCTACTCACACTTTTATGACGGGTTTTCTAAAGTACCGTTGAAAGATCAATCAGCGGAGCTTGGTGACTCACTTTACGGTGCTGCTTCCCTGAATGACTTTGGCATTTTGGCTGTGAGGGTGGTTAACGACCATAATCCAACCAAGGTCACTTCCAAGATTAGGGTGTACTTAAAACCCAAACACATCAGAGTGTGGTGCCCCCGCCCACCGAGGGCAGTGGCGTATTACGGTCCGGGAGTGGACTACAAGGATGGGACGCTCGCTCCCCTTTCCACCAAAGACCTGACCACGTAT";
            Polio[3] = "GGTTTGGGCCAGATGCTCGAGAGCATGATTGACAACACAGTCCGCGAAACAGTAGGGGCTTCAACCTCTCGGGACGCTCTCCCAAACACCGAGTCCAGCGGCCCAGCCCACTCCAAGGAAATTCCGGCGCTCACCGCAGTAGAGACGGGAGCCACAAACCCGTTGGTTCCTTCAGACACCGTACAAACTAGACATGTTATACAGCACAGATCGCGGTCAGAGTCCAGTGTTGAGTCCTTCTTCGCACGCGGTGCGTGTGTTACCATAATGACAGTGGACAATTCGGCCTCCACTACGTCAAAAGACAAGTTATTCTCTGTGTGGAAAATCACGTACAAGGACACTGTGCAGTTGAGGAGAAAATTAGAGTTTTTCACTTATTCCAGGTTTGACATGGAGTTCACTTTTGTAATCACAGCAAACTTTACAGAGACCAATAATGGACATGCTTTGAACCAGGTCTATCAAATCATGTATGTGCCGCCAGGCGCACCAGTGCCAGAAAAGTGGGATGATTATACTTGGCAAACATCATCGAACCCATCAATTTTCTACACATACGGCACAGCACCGGCCCGCATCTCCGTACCGTACGTTGGTATATCAAATGCCTACTCACACTTTTATGACGGGTTTTCTAAAGTACCGTTGAAAGATCAATCAGCGGAGCTTGGTGACTCACTTTACGGTGCTGCTTCCCTGAATGACTTTGGCATCTTGGCTGTGAGGGTGGTTAACGACCATAATCCAACCAAGGTCACTTCCAAGATTAGGGTGTACTTAAAACCCAAACACATCAGAGTGTGGTGCCCCCGCCCACCGAGGGCAGTGGCGTATTACGGTCCGGGAGTGGACTACAAGGATGGGACGCTCGCTCCCCTTTCCACCAAAGACCTGACCACGTAT";
            Polio[4] = "GGTTTGGGCCAGATGCTCGAGAGCATGATTGACAACACAGTCCGCGAAACAGTAGGGGCTTCAACCTCTCGGGACGCTCTCCCAAACACCGAGTCCAGCGGCCCAGCCCACTCCAAGGAAATTCCGGCGCTCACCGCAGTAGAGACGGGAGCCACAAACCCGTTGGTTCCCTCAGACACCGTACAAACTAGACATGTTATACAGCACAGATCGCGGTCAGAGTCCAGTGTTGAGTCCTTCTTCGCACGCGGTGCGTGTGTTACCATAATGACAGTGGACAATTCGGCCTCCACTACGTCAAAAGACAAGTTATTCTCTGTGTGGAAAATCACGTACAAGGACACTGTGCAGTTGAGGAGAAAATTAGAGTTTTTCACTTATTCCAGGTTTGACATGGAGTTTACTTTTGTAATCACAGCAAACTTTACAGAGACCAATAATGGACATGCTTTGAACCAGGTCTATCAAATCATGTATGTGCCACCAGGCGCACCAGTGCCAGAAAAGTGGGATGATTATACTTGGCAAACATCATCGAACCCATCAATTTTCTACACATACGGCACAGCACCGGCCCGCATCTCTATACCGTACGTTGGTATATCAAATGCCTACTCACACTTTTATGACGGGTTTTCTAAAGTACCATTGAAAGATCAATCAGCGGAGCTTGGTGACTCACTTTACGGTGCTGCTTCCCTGAATGACTTTGGCATTTTGGCTGTGAGGGTGGTTAACGACCATAATCCAACCAAGGTCACTTCCAAGATTAGGGTGTACTTAAAACCCAAACACATCAGAGTGTGGTGCCCCCGCCCACCGAGGGCAGTGGCGTATTACGGTCCGGGAGTGGACTACAAGGATGGGACGCTCGCTCCCCTTTCCACCAAAGACCTGACCACGTAT";
            Polio[5] = "GGTTTGGGCCAGATGCTCGAGAGCATGATTGACAACACAGTCCGCGAAACAGTAGGGGCTTCAACCTCTCGGGACGCTCTCCCAAACACCGAGTCCAGCGGCCCAGCCCACTCCAAGGAAATTCCGGCGCTCACCGCAGTAGAGACGGGAGCCACAAACCCGTTGGTTCCCTCAGACACCGTACAAACTAGACATGTTATACAGCACAGATCGCGGTCAGAGTCCAGTGTTGAGTCCTTCTTCGCACGCGGTGCGTGTGTTACCATAATGACAGTGGACAATTCGGCCTCCACTACGTCAAAAGATAAGTTATTCTCTGTGTGGAAAATCACGTACAAAGACACTGTGCAGTTGAGGAGAAAGTTAGAGTTTTTCACTTATTCCAGGTTTGACATGGAGTTCACTTTTGTAATCACAGCAAACTTTACAGAGACCAATAATGGACATGCTTTGAACCAGGTCTATCAAATCATGTATGTGCCACCAGGCGCACCAGTGCCAGAAAAGTGGGATGATTATACTTGGCAAACATCATCGAACCCATCAATTTTCTACACATACGGCACAGCACCGGCCCGCATCTCCGTACCGTACGTTGGTATATCAAATGCCTACTCACACTTTTACGACGGGTTTTCTAAAGTACCGTTGAAAGATCAATCAGCGGAGCTTGGTGACTCACTTTACGGTGCTGCTTCCCTGAATGACTTTGGCATTTTGGCTGTGAGGGTGGTTAACGACCATAACCCAACCAAGGTCACTTCCAAGATTAGGGTGTACTTAAAACCCAAACACATCAGAGTGTGGTGCCCCCGCCCACCGAGGGCAGTGGCGTATTACGGTCCGGGAGTGGACTACAAGGATGGGACGCTCGCTCCCCTTTCCACTAAAGACCTGACCACGTAC";
            Polio[6] = "GGTTTGGGCCAGATGCTCGAGAGCATGATTGACAACACAGTCCGCGAAACAGTAGGGGCTTCAACCTCTCGGGACGCTCTCCCAAACACCGAGTCCAGCGGCCCAGCCCACTCCAAGGAAATTCCGGCGCTCACCGCAGTAGAGACGGGAGCCACAAACCCGTTGGTTCCCTCAGACACCGTACAAACTAGACATGTTATACAGCACAGATCGCGGTCAGAGTCCAGTGTTGAGTCCTTCTTCGCACGCGGTGCGTGTGTTACCATAATGACAGTGGACAATTCGGCCTCCACTACGTCAAAAGATAAGTTATTCTCTGTGTGGAAAATCACGTACAAAGACACTGTGCAGTTGAGGAGAAAGTTAGAGTTTTTCACTTATTCCAGGTTTGACATGGAGTTCACTTTTGTAATCACAGCAAACTTTACAGAGACCAATAATGGACATGCTTTGAACCAGGTCTATCAAATCATGTATGTGCCACCAGGCGCACCAGTGCCAGAAAAGTGGGATGATTATACTTGGCAAACATCATCGAACCCATCAATTTTCTACACATACGGCACAGCACCGGCCCGCATCTCCGTACCGTACGTTGGTATATCAAATGCCTACTCACACTTTTACGACGGGTTTTCTAAAGTACCGTTGAAAGATCAATCAGCGGAGCTTGGTGACTCACTTTACGGTGCTGCTTCCCTGAATGACTTTGGCATTTTGGCTGTGAGGGTGGTTAACGACCATAACCCAACCAAGGTCACTTCCAAGATTAGGGTGTACTTAAAACCCAAACACATCAGAGTGTGGTGCCCCCGCCCACCGAGGGCAGTGGCGTATTACGGTCCGGGAGTGGACTACAAGGATGGGACGCTCGCTCCCCTTTCCACTAAAGACCTGACCACGTAC";
            Polio[7] = "GGTTTGGGCCAGATGCTCGAGAGCATGATTGACAACACAGTCCGCGAAACAGTAGGGGCTTCAACCTCTCGGGACGCTCTCCCAAACACCGAGTCCAGCGGCCCAGCCCACTCCAAGGAAATTCCGGCGCTCACCGCAGTAGAGACGGGAGCCACAAACCCGTTGGTTCCCTCAGACACCGTACAAACTAGACATGTTATACAGCACAGATCGCGGTCAGAGTCCAGTGTTGAGTCCTTCTTCGCACGCGGTGCGTGTGTTACCATAATGACAGTGGACAATTCGGCCTCCACTACGTCAAAAGATAAGTTATTCTCTGTGTGGAAAATCACGTACAAAGACACTGTGCAGTTGAGGAGAAAGTTAGAGTTTTTCACTTATTCCAGGTTTGACATGGAGTTCACTTTTGTAATCACAGCAAACTTTACAGAGACCAATAATGGACATGCTTTGAACCAGGTCTATCAAATCATGTATGTGCCACCAGGCGCACCAGTGCCAGAAAAGTGGGATGATTATACTTGGCAAACATCATCGAACCCATCAATTTTCTACACATACGGCACAGCACCGGCCCGCATCTCCGTACCGTACGTTGGTATATCAAATGCCTACTCACACTTTTACGACGGGTTTTCTAAAGTACCGTTGAAAGATCAATCAGCGGAGCTTGGTGACTCACTTTACGGTGCTGCTTCCCTGAATGACTTTGGCATTTTGGCTGTGAGGGTGGTTAACGACCATAACCCAACCAAGGTCACTTCCAAGATTAGGGTGTACTTAAAACCCAAACACATCAGAGTGTGGTGCCCCCGCCCACCGAGGGCAGTGGCGTATTACGGTCCGGGAGTGGACTACAAGGATGGGACGCTCGCTCCCCTTTCCACTAAAGACCTGACCACGTAC";
            Polio[8] = "GGTTTGGGCCAGATGCTCGAGAGCATGATTGACAACACAGTCCGCGAGACAGTAGGGGCTTCAACCTCTCGGGACGCTCTCCCAAACACCGAGCCCAGCGGCCCAGCCCACTCCAAGGAAATTCCGGCGCTCACCGCAGTAGAGACGGGAGCCACAAACCCGTTAGTTCCCTCAGACACCGTACAAACTAGACATGTTATACAGCACAGATCGCGGTCAGAGTCCAGTGTTGAGTCCTTCTTCGCACGCGGTGCGTGTGTTACCATAATGACAGTGGACAATTCGGCCTCCACTACGTCAAAAGACAAGTTATTCTCTGTGTGGAAAATCACGTACAAGGACACTGTGCAGTTGAGGAGAAAATTAGAGTTTTTCACTTATTCCAGGTTTGACATGGAATTCACTTTTGTAATCACAGCAAACTTTACAGAGACCAATAATGGACATGCTTTGAACCAGGTCTATCAAATCATGTATGTGCCACCAGGCGCACCAGTGCCAGAAAAGTGGGATGATTACACTTGGCAAACATCATCGAACCCATCAATTTTCTACACATACGGCACAGCACCGGCCCGCATCTCCGTACCATACATTGGTATATCAAATGCCTACTCACACTTTTATGACGGGTTTTCTAAAGTACCGTTGAAAGATCAATCAGCGGAGCTTGGTGACTCACTTTACGGTGCTGCTTCCCTGAATGACTTTGGCATTTTGGCTGTGAGGGTGGTTAACGACCATAATCCAACCAAGGTCACTTCCAAGATTAGGGTGTACTTAAAACCCAAACACATCAGAGTGTGGTGCCCCCGCCCACCGAGGGCAGTGGCGTATTACGGTCCGGGAGTGGATTACAAGGATGGGACGCTTGCTCCCCTTTCCACCAAAGACCTGATCACGTAT";
            Polio[9] = "GGTTTGGGCCAGATGCTCGAGAGCGTGATTGACAACACAGTCCGCGAAACAGTAGGGGCTTCAACCTCTCGGGACGCTCTCCCAAATACCGAGTCCAGCGGCCCAGCCCACTCCAAGGAAATTCCGGCGCTCACCGCAGTAGAGACGGGAGCCACAAACCCGCTGGTTCCCTCAGACACCGTACAAACTAGACATGTTATACAGCACAGATCGCGGTCAGAGTCCAGTGTTGAGTCCTTCTTCGCACGCGGTGCGTGTGTTACCATAATGACAGTGGACAATTCGGCCTCCACTACGTCAAAAGATAAGTTATTCTCTGTGTGGAAAATCACGTACAAAGACACTGTGCAGTTGAGGAGAAAGTTAGAGTTTTTCACTTATTCCAGGTTTGACATGGAGTTCACTTTTGTAATCACAGCAAACTTTACAGAGACCAATAATGGACATGCTTTGAACCAGGTCTATCAAATCATGTATGTGCCACCAGGCGCACCAGTGCCAGGAAAGTGGGATGATTATACTTGGCAAACATCATCGAACCCATCAATTTTCTACACATACGGCACAGCACCGGCCCGCATCTCCGTACCGTACGTTGGTATATCAAATGCCTACTCACACTTTTACGACGGGTTTTCTAAAGTACCGTTGAAAGATCAATCAGCGGAGCTTGGTGACTCACTTTACGGTGCTGCTTCCCTGAATGACTTTGGCATTTTGGCTGTGAGGGTGGTTAACGACCATAACCCAACCAAGGTCACTTCCAAGATTAGGGTGTACTTAAAACCCAAACACATCAGAGTGTGGTGCCCCCGCCCACCGAGGGCAGTGGCGTATTACGGTCCGGGAGTGGACTACAAGGATGGGACGCTCGCTCCCCTTTCCACTAAAGACCTGACCACGTAC";

            for(int i = 0; i < Polio.Length; i++)
                for(int j = 0; j < Polio.Length; j++)
                {
                    if(i != j)
                    {
                        listBoxComp.Items.Add("Образцы i = " + i + " и j = " + j + " совпадают на " + compare2Polio(Polio[i], Polio[j]) + "%");
                    }
                }

            label1.Content = comboBox.SelectedIndex;
            double[] a = new double[9];
            int k = 0;
            for (int i = 0; i < 10; i++)
                if (i != comboBox.SelectedIndex)
                {
                    a[k] = i;
                    k++;
                }
            label2.Content = a[0] + ", " + compare2Polio(Polio[comboBox.SelectedIndex], Polio[Convert.ToInt32(a[0])]) + "%";
            label3.Content = a[1] + ", " + compare2Polio(Polio[comboBox.SelectedIndex], Polio[Convert.ToInt32(a[1])]) + "%";
            label4.Content = a[2] + ", " + compare2Polio(Polio[comboBox.SelectedIndex], Polio[Convert.ToInt32(a[2])]) + "%";
            label5.Content = a[3] + ", " + compare2Polio(Polio[comboBox.SelectedIndex], Polio[Convert.ToInt32(a[3])]) + "%";
            label6.Content = a[4] + ", " + compare2Polio(Polio[comboBox.SelectedIndex], Polio[Convert.ToInt32(a[4])]) + "%";
            label7.Content = a[5] + ", " + compare2Polio(Polio[comboBox.SelectedIndex], Polio[Convert.ToInt32(a[5])]) + "%";
            label8.Content = a[6] + ", " + compare2Polio(Polio[comboBox.SelectedIndex], Polio[Convert.ToInt32(a[6])]) + "%";
            label9.Content = a[7] + ", " + compare2Polio(Polio[comboBox.SelectedIndex], Polio[Convert.ToInt32(a[7])]) + "%";
            label10.Content = a[8] + ", " + compare2Polio(Polio[comboBox.SelectedIndex], Polio[Convert.ToInt32(a[8])]) + "%";
        }
    }
}
